### ISSUE TITLE
TreeGrid renders flat hierarchy

### ISSUE THREAD

**Issue by mcooper7290** [vaadin/tree-grid#22] opened 2017-03-10 23:23 UTC
I've built my first TreeGrid component and I can't get TreeGrid to display the hierarchy.  The table is rendered flat without any tree structure.

The debug in my container class indicates the items are added with the proper hierarchy.

I'm using TreeGrid 0.7.4 and Vaadin 7.7.7.

The class files are available in this forum post:
https://vaadin.com/forum#!/thread/15399932

**Comment by wbadam** [comment] 2017-03-11 07:28
Hi, I answered your forum post, please take a look if it helps.

**Comment by mcooper7290** [comment] 2017-03-14 23:06
Unfortunately that's not the issue.  More details in the forum post.

**Comment by wbadam** [comment] 2017-05-18 07:21
Hi, sorry I didn't get back.

As I answered in the forum, it is probably caused by your css not built correctly. Please try run `mvn clean install` that should fix all style and widgetset dependencies that you have if your `pom.xml` configurations are right. Alternatively, please run `vaadin:compile-theme` and `vaadin:update-theme` goals.

I'm closing the ticket since it is not a bug, but if you have more questions, please feel free to ask them and I'll try to answer as soon as I can.

**Closed as completed by wbadam** 2017-05-18 07:21 UTC
