### ISSUE TITLE
Bug display in TreeGrid

### ISSUE THREAD

**Issue by rabat22** [vaadin/tree-grid#13] opened 2017-02-02 10:22 UTC
I have a problem with your add-on Vaadin.

I have a grid in a window. The grid contains two parent node and each parent node contains some child node. 

![image](https://cloud.githubusercontent.com/assets/25502578/22545039/7eec3ab0-e937-11e6-9ada-45080998d4eb.png)

When all nodes are fold up and I unfold one node, I can have a bug display in treegrid like this

![image](https://cloud.githubusercontent.com/assets/25502578/22545200/14421e2c-e938-11e6-84e3-ebb08338876d.png)

![image](https://cloud.githubusercontent.com/assets/25502578/22545219/23cd5e24-e938-11e6-9cec-6e6bdbe2e40c.png)

Nevertheless, I don't have this problem when the grid is not in a window and when I use Chrome. The problem is just with IE.

![image](https://cloud.githubusercontent.com/assets/25502578/22545561/86d8f040-e939-11e6-9e18-faed465d457e.png)

[TreeGridTest.zip](https://github.com/vaadin/tree-grid/files/747422/TreeGridTest.zip)

Sincerely.

**Comment by wbadam** [comment] 2017-02-02 10:39
Hi, thanks for the feedback and the example app. Will take a look as soon as I can.
Which IE version are you using?

**Comment by rabat22** [comment] 2017-02-02 10:44
Hi,

I use IE 11 (version 11.576.14393.0).

Sincerely.

**Comment by rabat22** [comment] 2017-02-13 12:13
Do you have the time to see my problem that i send you before.

**Comment by wbadam** [comment] 2017-02-22 06:35
Hi,

Sorry I didn't have time yet, will try to take a look this week.

What may help debugging, did you experience similar issues with `Grid` in any situation? Since `TreeGrid` is a subclass of `Grid`, often such issues are a bug in the superclass.

Thanks, and I'll let you know when I find something.
Adam

**Comment by wbadam** [comment] 2017-02-25 19:30
Verified on IE 11

It is probably the same framework bug as in https://github.com/vaadin/framework/issues/7883
I'll try to narrow down the cause.

**Comment by wbadam** [comment] 2017-02-26 13:40
This is most certainly a framework bug. It means that it needs to be fixed in the framework.
I'll close this now, please follow vaadin/framework#7883 for further details.

**Closed as completed by wbadam** 2017-02-26 13:40 UTC
Labels: Framework bug
